# Default values for guardian-angel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# guardian-angel configurables

# Network
localNetwork: '192.168.4.0/24'

# Lookup service
lookupHostName: 'guardian-angel'
internalHttpPort: 3000
safeSearchEnforced: false
guardianConfigDir: '/opt/guardian'
guardianReplicas: 1

# Filter
proxyHostName: 'webfilter'
squidInternalPort: 3128
squidPublicPort: 30128
icapInternalPort: 1344
squidConfigDir: '/etc/squid'
transparent: false
decryptHTTPS: false
allowRules:
- category: all
  allow: true
decryptRules:
- category: all
  decrypt: false
e2guardianConfigDir: '/opt/etc/e2guardian'
e2guardianConf:
  defaultConfig: false # include e2guardian default lists
  phraseLists: []
  weightedPhraseLists: []
  lists: []
filterReplicas: 1

# DNS
publicDnsPort: 9053
reverseDnsPort: 53
reverseDnsReplicas: 3

# Postgres
authDbHost: 'auth-db'
persistentDbPath: '/var/lib/postgresql/data/pgdata'
postgresUser: 'acluser'
postgresDbName: 'acls'
dbInternalPort: 27017
dbServicePort: 5432
dbPassword: "DB_PASSWORD"
guardianDbReplicas: 1

# Redis config
redisHost: 'redis'
redisPort: 6379
redisPassword: "REDIS_PASSWORD"
redisReplicas: 1

# Cache config
cacheTTL: 90
maxKeys: 8192

# Kubernetes-related

aclVolumeSize: 4Gi
dbVolumeSize: 4Gi
phraseVolumeSize: 4Gi
