apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dns-fwd
  labels:
    app: dns-fwd
spec:
  selector:
    matchLabels:
      app: dns-fwd
  template:
    metadata:
      labels:
        app: dns-fwd
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: unbound
          image: 'jusschwa/unbound-reversecache:{{ .Values.releaseTag }}'
          ports:
            - containerPort: {{ .Values.publicDnsPort }}
              protocol: UDP
            - containerPort: {{ .Values.publicDnsPort }}
              protocol: TCP
          env:
            - name: FORWARDER
              value: 'true'

