apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-reverse
  labels:
    app: dns-reverse
spec:
  replicas: {{ .Values.reverseDnsReplicas }}
  selector:
    matchLabels:
      app: dns-reverse
  template:
    annotations:
      redispass/hash: {{ .Values.redisPassword | sha1sum | quote }}
      safesearch: {{ .Values.safeSearchEnforced | toString }}
    metadata:
      labels:
        app: dns-reverse
    spec:
      containers:
        - name: unbound
          image: 'jusschwa/unbound-reversecache:latest'
          ports:
            - containerPort: {{ .Values.publicDnsPort }}
              protocol: UDP
            - containerPort: {{ .Values.publicDnsPort }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: redis-pass
          volumeMounts:
            - mountPath: {{ .Values.guardianConfigDir }}
              name: guardian-conf-volume
      volumes:
        - name: guardian-conf-volume
          configMap:
            name: guardian-conf
