apiVersion: v1
data:
{{- range .Values.e2guardianConf.phraseLists }}
{{- $list := . -}}
{{ print "\n  "}}{{ $list.listName }}: |
{{- range $list.groups }}
{{- $group := . -}}
{{- if $group.name }}
{{print "\n    "}}#listcategory: {{ $group.name }}
{{- end }}
{{- range $group.phrases }}
{{- $phrase := . -}}
{{print "\n    "}}<{{ join ">,<" $phrase.phrase }}>
{{- end }}
{{- end }}
{{- end }}

{{- range .Values.e2guardianConf.weightedPhraseLists }}
{{- $list := . -}}
{{ print "\n  "}}{{ $list.listName }}: |
{{- range $list.groups }}
{{- $group := . -}}
{{- if $group.name }}
{{print "\n    "}}#listcategory: {{ $group.name }}
{{- end }}
{{- range $group.phrases }}
{{- $phrase := . -}}
{{print "\n    "}}<{{ join ">,<" $phrase.phrase }}><{{ $phrase.weight }}>
{{- end }}
{{- end }}
{{- end }}
kind: ConfigMap
metadata:
  name: e2guardian-phrases
