apiVersion: apps/v1
kind: Deployment
metadata:
  name: webfilter
  labels:
    app: webfilter
spec:
  replicas: {{ .Values.filterReplicas }}
  selector:
    matchLabels:
      app: webfilter
  template:
    metadata:
      annotations:
        allowrules/hash: {{ .Values.allowRules | sha1sum | quote }}
        decryptrules/hash: {{ .Values.decryptRules | sha1sum | quote }}
        e2gconf/hash: {{ .Values.e2guardianConfig | sha1sum | quote }}
      labels:
        app: webfilter
    spec:
      containers:
        - name: squid
          image: 'jusschwa/squid-ssl:latest'
          ports:
            - containerPort: {{ .Values.squidInternalPort }}
          volumeMounts:
            - mountPath: {{ .Values.guardianConfigDir }}
              name: guardian-conf-volume
{{- if eq .Values.decryptHTTPS true }}
	    - mountPath: {{ .Values.squidConfigDir }}/ssl
              name: guardian-tls-volume
        - name: e2guardian
          image: 'jusschwa/e2guardian-icap:latest'
          ports:
            - containerPort: {{ .Values.icapInternalPort }}
          volumeMounts:
            - mountPath: {{ .Values.guardianConfigDir }}
              name: guardian-conf-volume
            - mountPath: {{ .Values.phraseDir }}
              name: guardian-phrases
{{- end }}
      volumes:
        - name: guardian-conf-volume
          configMap:
            name: guardian-conf
{{- if eq .Values.decryptHTTPS true }}
        - name: guardian-tls-volume
          secret:
            secretName: guardian-tls
{{- end }}
        - name: guardian-phrases
          persistentVolumeClaim:
            claimName: phrases-pvc
