apiVersion: apps/v1
kind: Deployment
metadata:
  name: webfilter
  labels:
    app: webfilter
spec:
  replicas: {{ .Values.filterReplicas }}
  selector:
    matchLabels:
      app: webfilter
  template:
    metadata:
      annotations:
        allowrules/hash: {{ .Values.allowRules | toString | sha1sum | quote }}
        decryptrules/hash: {{ .Values.decryptRules | toString | sha1sum | quote }}
        e2gconf/hash: {{ .Values.e2guardianConfig | sha1sum | quote }}
{{- if .Values.tls }}
        cert/hash: {{ .Values.tls.cert | sha1sum | quote }}
        key/hash: {{ .Values.tls.key | sha1sum | quote }}
{{- end }}
      labels:
        app: webfilter
    spec:
      containers:
        - name: squid
          image: 'jusschwa/squid-ssl:helmconfig'
          env:
            - name: LOOKUP_HOST
              value: '{{ .Values.lookupHostName }}'
            - name: LOOKUP_PORT
              value: '{{ .Values.internalHttpPort | toString }}'
          ports:
            - containerPort: {{ .Values.squidInternalPort }}
          volumeMounts:
            - mountPath: /tmpl
              name: squid-conf-volume
{{- if eq .Values.decryptHTTPS true }}
            - mountPath: {{ .Values.squidConfigDir }}/ssl
              name: guardian-tls-volume
        - name: e2guardian
          image: 'jusschwa/e2guardian-icap:latest'
          ports:
            - containerPort: {{ .Values.icapInternalPort }}
          volumeMounts:
            - mountPath: {{ .Values.guardianConfigDir }}
              name: guardian-conf-volume
            - mountPath: {{ .Values.phraseDir }}
              name: guardian-phrases
{{- end }}
      volumes:
        - name: guardian-conf-volume
          configMap:
            name: guardian-conf
        - name: squid-conf-volume
          configMap:
            name: squid-conf
{{- if eq .Values.decryptHTTPS true }}
{{- if .Values.tls }}
        - name: guardian-tls-volume
          secret:
            secretName: guardian-tls
{{- end }}
{{- end }}
        - name: guardian-phrases
          persistentVolumeClaim:
            claimName: phrases-pvc
