kind: ConfigMap
apiVersion: v1
metadata:
  name: guardian-conf
data:
  guardian.json: |
    {
      "proxyPort": {{ .Values.squidInternalPort }},
      "e2guardianConfigDir": "{{ .Values.e2guardianConfigDir }}",
      "transparent": {{ .Values.transparent }},
      "sslBumpEnabled": {{ .Values.decryptHTTPS }},
      "redisConfig": {
        "host": "{{ .Values.redisHost }}",
        "port": {{ .Values.redisPort }}
      },
      "cacheConfig": {
        "ttl": {{ .Values.cacheTTL }},
        "maxKeys": {{ .Values.maxKeys }}
      },
      "proxyHost": "{{ .Values.proxyHostName }}",
      "httpPort": {{ .Values.internalHttpPort }},
      "safeSearchEnforced": {{ .Values.safeSearchEnforced }},
      "allowRules": {{ .Values.allowRules | toJson }},
      "authDb": {
        "host": "{{ .Values.authDbHost }}"
      },
      "decryptRules": {{ .Values.decryptRules | toJson }},
      "helper": {
        "host": "{{ .Values.lookupHostName }}",
        "port": {{ .Values.internalHttpPort }}
      }
    }
