{{- if .Values.tls }}
apiVersion: v1
data:
  tls.crt: {{ .Values.tls.cert }}
  tls.key: {{ .Values.tls.key }}
kind: Secret
metadata:
  name: guardian-tls
  namespace: filter
type: kubernetes.io/tls
{{- end }}
