apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: guardian-ca
  namespace: filter
spec:
  isCA: true
  commonName: {{ .Values.commonName }}
  secretName: guardian-ca-tls
{{- if .Values.IpSANs }}
  ipAddresses: {{ .Values.IpSANs }}
{{- end }}
{{- if .Values.dnsSANs }}
  dnsNames: {{ .Values.dnsNames }}
{{- end }}
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io