apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: guardian-ca
  namespace: filter
spec:
  isCA: true
  commonName: {{ .Values.commonName }}
  secretName: guardian-ca-tls
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io