kind: ConfigMap
apiVersion: v1
metadata:
  name: guardian-conf
data:
  guardian.json: |
    {
      "redisConfig": {
        "host": "{{ .Values.redisHost }}",
        "port": {{ .Values.redisPort }}
      },
      "cacheConfig": {
        "ttl": {{ .Values.cacheTTL }},
        "maxKeys": {{ .Values.maxKeys }}
      },
      "httpPort": {{ .Values.internalHttpPort }}
    }
