{{- if eq .Values.decryptHTTPS true }}
apiVersion: v1
data:
  tls.crt: {{ .Values.tls.cert }}
  tls.key: {{ .Values.tls.key }}
kind: Secret
metadata:
  name: guardian-tls
type: kubernetes.io/tls
{{- end }}