apiVersion: v1
kind: Service
metadata:
  name: guardian-db
spec:
  selector:
    app: guardian-db
  ports:
    - name: guardian-db
      protocol: TCP
      port: {{ .Values.dbServicePort }}
      targetPort: {{ .Values.dbServicePort }}
