apiVersion: apps/v1
kind: Deployment
metadata:
  name: guardian-angel
  labels:
    app: guardian-angel
spec:
  replicas: {{ .Values.guardianReplicas }}
  selector:
    matchLabels:
      app: guardian-angel
  template:
    metadata:
      annotations:
        redispass/hash: {{ .Values.redisPassword | sha1sum | quote }}
        dbpass/hash: {{ .Values.dbPassword | sha1sum | quote }}
{{- if eq .Values.safeSearchEnforced true }}
        safesearch/enforced: 'yes'
{{- else }}
        safesearch/enforced: 'no'
{{- end }}
      labels:
        app: guardian-angel
    spec:
      containers:
        - name: guardian-angel
          image: 'jusschwa/guardian-angel:{{ .Values.releaseTag }}'
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.internalHttpPort }}
          volumeMounts:
            - mountPath: {{ .Values.guardianConfigDir }}/conf
              name: guardian-conf-volume
          envFrom:
            - secretRef:
                name: redis-pass
            - secretRef:
                name: guardian-db-creds
      volumes:
        - name: guardian-conf-volume
          configMap:
            name: guardian-conf
