{{- if eq .Values.decryptHTTPS true }}

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: guardian-cert
  namespace: filter
spec:
  isCA: true
  commonName: {{ .Values.commonName }}
  secretName: guardian-tls
  duration: 2160h
  renewBefore: 72h
  subject:
    organizations:
      - {{ .Values.organization }}
    countries:
      - {{ .Values.country }}
    provinces:
      - {{ .Values.state }}
    localities:
      - {{ .Values.locality }}
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: guardian-ca-issuer
    kind: Issuer
    group: cert-manager.io

{{- end }}