apiVersion: v1
kind: Service
metadata:
  name: guardian-angel
  labels:
    app: guardian-angel
spec:
  selector:
    app: guardian-angel
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.internalHttpPort }}
      targetPort: {{ .Values.internalHttpPort }}
