apiVersion: apps/v1
kind: Deployment
metadata:
  name: guardian-db
  labels:
    app: guardian-db
spec:
  replicas: {{ .Values.guardianDbReplicas }}
  selector:
    matchLabels:
      app: guardian-db
  template:
    metadata:
      annotations:
        dbpass/hash: {{ .Values.dbPassword | sha1sum | quote }}
      labels:
        app: guardian-db
    spec:
      containers:
        - name: postgres
          image: 'postgres:latest'
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: {{ .Values.persistentDbPath }}
              name: guardian-db
          envFrom:
            - secretRef:
                name: guardian-db-creds
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresUser }}
            - name: PGDATA
              value: {{ .Values.persistentDbPath }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresDbName }}
          ports:
            - containerPort: {{ .Values.dbInternalPort }}
      volumes:
        - name: guardian-db
          persistentVolumeClaim:
            claimName: guardian-db-pvc
