apiVersion: v1
kind: Service
metadata:
  name: guardian-nginx
spec:
  selector:
    app: guardian-nginx
  ports:
    - name: guardian-nginx
      protocol: TCP
      port: {{ .Values.webHttpsPort }}
      targetPort: {{ .Values.webHttpsPort }}
