apiVersion: apps/v1
kind: Deployment
metadata:
  name: guardian-nginx
  labels:
    app: guardian-nginx
spec:
  replicas: {{ .Values.nginxReplicas }}
  selector:
    matchLabels:
      app: guardian-nginx
  template:
    metadata:
      labels:
        app: guardian-nginx
    spec:
      containers:
        - name: guardian-nginx
          image: 'jusschwa/guardian-nginx:{{ .Values.releaseTag }}'
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.webHttpsPort }}
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/ssl
              name: nginx-tls-volume
      volumes:
        - name: nginx-tls-volume
          secret:
            secretName: nginx-tls-secret

