apiVersion: v1
kind: Service
metadata:
  name: guardian-nginx
  labels:
    app: guardian-nginx
spec:
  type: NodePort
  selector:
    app: guardian-nginx
  ports:
    - name: guardian-nginx
      protocol: TCP
      port: {{ .Values.webHttpsPort }}
      targetPort: {{ .Values.webHttpsPort }}
      nodePort: {{ .Values.webHttpsPublicPort }}
