apiVersion: v1
kind: Service
metadata:
  name: guardian-nginx
  labels:
    app: guardian-nginx
spec:
  type: NodePort
  selector:
    app: guardian-nginx
  ports:
    - name: https
      protocol: TCP
      port: {{ .Values.webHttpsPort }}
      targetPort: {{ .Values.webHttpsPort }}
      nodePort: {{ .Values.webHttpsPublicPort }}
    - name: http
      protocol: TCP
      port: {{ .Values.webHttpPort }}
      targetPort: {{ .Values.webHttpPort }}
      nodePort: {{ .Values.webHttpPublicPort }}
