apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: {{ .Values.redisReplicas }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: 'jusschwa/redis:latest'
          ports:
            - containerPort: {{ .Values.redisPort }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: redis-pass
