{{- if eq .Values.decryptHTTPS true }}
apiVersion: v1
data:
  tls.crt: {{ .Values.tlsCert }}
  tls.key: {{ .Values.tlsKey }}
kind: Secret
metadata:
  name: guardian-tls
type: kubernetes.io/tls
{{- end }}