{{- if eq .Values.transparent true }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: transocks
  labels:
    app: transocks
spec:
  selector:
    matchLabels:
      app: transocks
  template:
    metadata:
      labels:
        app: transocks
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: transocks
          image: jusschwa/transocks-proxy
{{- end }}
